{{- if .Values.magnus.enabled }}
{{- with .Values.magnus }}
{{- $fullName := printf "%s-%s" (include "jumpserver.fullname" $) "jms-magnus" }}
{{- $containerName := "jms-magnus" }}
{{- $image := printf "%s" (include "jumpserver.magnusImage" $) }}
{{- $mysqlPort := printf "%s" (include "jumpserver.magnus.mysql.port" $) }}
{{- $mariadbPort := printf "%s" (include "jumpserver.magnus.mariadb.port" $) }}
{{- $redisPort := printf "%s" (include "jumpserver.magnus.redis.port" $) }}
{{- $postgresqlPort := printf "%s" (include "jumpserver.magnus.postgresql.port" $) }}
{{- $oraclePorts := printf "%s" (include "jumpserver.magnus.oracle.ports" $) }}
{{- $oraclePortStart := printf "%s" (include "jumpserver.magnus.oracle.port.start" $) | int }}
{{- $oraclePortEnd := printf "%s" (include "jumpserver.magnus.oracle.port.end" $) | int }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "jumpserver.labels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      {{- toYaml .labels | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        {{- toYaml .labels | nindent 8 }}
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml $.Values.global.imagePullSecrets }}
      {{- end }}
      serviceAccountName: {{ template "jumpserver.serviceAccountName" $ }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $containerName }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: {{ $image }}
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- with .command }}
          command:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          env:
            - name: CORE_HOST
              value: "http://{{ include "jumpserver.fullname" $ }}-jms-core:{{ $.Values.core.service.web.port }}"
            - name: BOOTSTRAP_TOKEN
              value: {{ $.Values.core.config.bootstrapToken | quote }}
            - name: LOG_LEVEL
              value: {{ .config.log.level | quote }}
            - name: MAGNUS_MYSQL_PORT
              value: {{ $mysqlPort | quote }}
            - name: MAGNUS_MARIADB_PORT
              value: {{ $mariadbPort | quote }}
            - name: MAGNUS_REDIS_PORT
              value: {{ $redisPort | quote }}
            - name: MAGNUS_POSTGRESQL_PORT
              value: {{ $postgresqlPort | quote }}
            - name: MAGNUS_ORACLE_PORTS
              value: {{ $oraclePorts | quote }}
            {{- range $key, $val := .env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          ports:
            - name: mysql
              containerPort: {{ $mysqlPort }}
              protocol: TCP
            - name: mariadb
              containerPort: {{ $mariadbPort }}
              protocol: TCP
            - name: redis
              containerPort: {{ $redisPort }}
              protocol: TCP
            - name: postgresql
              containerPort: {{ $postgresqlPort }}
              protocol: TCP
            {{- range $port := untilStep $oraclePortStart $oraclePortEnd 1 }}
            - name: oracle-{{ $port }}
              containerPort: {{ $port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/opt/magnus/data"
              name: "jms-magnus-data"
              {{- if .persistence.subPath }}
              subPath: {{ .persistence.subPath | quote }}
              {{- end }}
          {{- with .volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      volumes:
        - persistentVolumeClaim:
            {{- if .persistence.existingClaim }}
            claimName: {{ .persistence.existingClaim | quote }}
            {{- else }}
            claimName: '{{ include "jumpserver.fullname" $ }}-jms-magnus-data'
            {{- end }}
          name: "jms-magnus-data"
      {{- with .volumes }}
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
{{- end }}
